---
# Есть известная проблема что OpenConnect сервер версии 1.1.3 в Ubuntu 22.04 имеет
# неприятный баг который до сих пор не исправлен ... Будем ставить из исходников.
#
# https://bugs.launchpad.net/ubuntu/+source/ocserv/+bug/1975550
- name: "Check if OpenConnect server is installed"
  command: "which ocserv"
  changed_when: false
  failed_when: "ocserv_installed.rc not in [0, 1]"
  register: "ocserv_installed"

- name: "Install OpenConnect server"
  vars:
    directory: "/tmp/ocserv"

    required_packages:
      - "libev4"
      - "libreadline8"
      - "libhttp-parser2.9"
      - "liblz4-1"
      - "libtalloc2"
      - "libseccomp2"
      - "libgnutls30"

    build_packages:
      - "autoconf"
      - "automake"
      - "pkg-config"
      - "gcc"
      - "make"
      - "protobuf-compiler"
      - "protobuf-c-compiler"
      - "libgnutls28-dev"
      - "libev-dev"
      - "libprotobuf-c-dev"
      - "libreadline-dev"
      - "libhttp-parser-dev"
      - "liblz4-dev"
      - "libseccomp-dev"
      - "libpam0g-dev"
      - "libtalloc-dev"
      - "gperf"
      - "iperf3"
      - "lcov"
  block:
    - name: "Create {{ directory }}"
      ansible.builtin.file:
        path: "{{ directory }}"
        state: "directory"

    - name: "Install required packages"
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: "present"
        update_cache: true

    - name: "Install build packages"
      ansible.builtin.apt:
        name: "{{ build_packages }}"
        state: "present"

    - name: "Clone OpenConnect server repository to {{ directory }}"
      ansible.builtin.git:
        repo: "https://gitlab.com/openconnect/ocserv.git"
        depth: 1
        dest: "{{ directory }}"
        version: "1.1.6"

    - name: "Generate configuration scripts"
      ansible.builtin.command:
        cmd: "autoreconf -fvi"
        chdir: "{{ directory }}"

    - name: "Configure"
      ansible.builtin.command:
        cmd: "./configure"
        chdir: "{{ directory }}"
      failed_when: false

    - name: "Build & install"
      community.general.make:
        targets:
          - "all"
          - "install"
        chdir: "{{ directory }}"

    - name: "Copy systemd unit"
      ansible.builtin.template:
        src: "unit.j2"
        dest: "/etc/systemd/system/ocserv.service"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Configure PAM"
      ansible.builtin.template:
        src: "pam.j2"
        dest: "/etc/pam.d/ocserv"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Create required directories"
      ansible.builtin.file:
        path: "/etc/ocserv"
        state: "directory"

    - name: "Remove build packages"
      ansible.builtin.apt:
        name: "{{ build_packages }}"
        state: "absent"

    - name: "Remove directory with repository"
      ansible.builtin.file:
        path: "{{ directory }}"
        state: "absent"

  when: "ocserv_installed.rc != 0"
